name: CI/CD Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    name: Test & Build
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests (if any)
        run: npm test --if-present
        
      - name: Lint code
        run: npm run lint --if-present
        
      - name: Build application
        run: npm run make
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-build
          path: out/
          retention-days: 30

  release:
    name: Create Release
    needs: test
    runs-on: windows-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build for release
        run: npm run make
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/make/squirrel.windows/x64/*.exe
            out/make/squirrel.windows/x64/*.nupkg
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install API dependencies
        run: |
          cd api_complete
          npm ci
          
      - name: Test API
        run: |
          cd api_complete
          npm test --if-present
          
      - name: Build API documentation
        run: |
          cd api_complete
          npm run docs --if-present
