name: PR Quality Checks

on:
  pull_request:
    branches: [ master, main ]

jobs:
  quality-checks:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint --if-present
        
      - name: Run security audit
        run: npm audit --audit-level=moderate
        
      - name: Check for vulnerabilities
        run: npm audit --audit-level=high
        
      - name: Build check
        run: npm run make
        
      - name: Test build artifacts
        run: |
          if [ -d "out" ]; then
            echo "✅ Build artifacts created successfully"
            ls -la out/
          else
            echo "❌ No build artifacts found"
            exit 1
          fi
